export const CATEGORIES = [
  "Finance & Accounting",
  "Technology & Engineering",
  "Marketing & Sales",
  "Operations & Supply Chain",
  "Human Resources",
  "Legal & Compliance",
  "Executive Leadership",
  "Strategy & Consulting",
  "Healthcare & Life Sciences",
  "Sustainability & ESG",
  "Education & Training",
  "Data & Analytics",
  "Architecture & Construction",
  "Energy & Utilities",
  "Real Estate & Property",
  "Hospitality & Tourism",
  "Retail & E-commerce",
  "Non-profit & Social Impact",
  "Manufacturing",
  "Other",
];
